<?php

namespace OAH\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

	public function getArticles($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
	  ->leftjoin('a.categories', 'c')
	  ->addSelect('c')
	  ->leftjoin('a.image', 'i')
	  ->addselect('i')
	  ->leftjoin('a.commentaires','com')
	  ->addSelect('com')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
	
	$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
	;
		
	return new Paginator($query, true);
	
   }

   public function getAvecCategories ($page ,$slug, $nbPerPage )
   { 
   $query = $this -> createQueryBuilder ('a')
   	   ->leftjoin ( 'a.categories' , 'c' ) 
       ->addselect('c')
       ->where('c.slug = :slug')
       ->setParameter('slug', $slug)
       ->leftjoin('a.image', 'i')
	   ->addselect('i')
	   ->orderBy('a.date', 'DESC')
       ->getQuery() 
      ;

      $query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
	;
		
	return new Paginator($query, true);
 
	} 
}
