<?php

namespace OAH\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

	public function getArticles($page, $nbPerPage)
  {
    $query = $this->createQueryBuilder('a')
	  ->leftjoin('a.categories', 'c')
	  ->addSelect('c')
	  ->leftjoin('a.image', 'i')
	  ->addselect('i')
	  ->leftjoin('a.commentaires','com')
	  ->addSelect('com')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;
	
	$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
	;
		
	return new Paginator($query, true);
	
   }

   public function getAvecCategories ( array $nom )
   { 
   $qb = $this -> createQueryBuilder ( 'a' );
   
   // On fait une jointure avec l'entité Categorie, avec pour alias « c »
   $qb -> join ( 'a.categorie' , 'c' ) 
       -> addselct('c')
       -> where('c.nom = :nom')
       ->setParameter('nom', $nom); 
	   //-> where ( $qb -> expr () -> in ( 'c.nom' , $nom ));
	   // Puis on filtre sur le nom des catégories à l'aide d'un IN
	   
	   // Enfin, on retourne le résultat 
	 return $qb -> getQuery () -> getResult ();
	} 
}
