OAHNews_accueil:
    path:     /{page}
    defaults: { _controller: OAHNewsBundle:News:index , page: 1 }
    requirements:
        page: \d*

OAHNews_voir:
    path:     /article/{slugarticle}
    defaults: { _controller: OAHNewsBundle:News:voir }

OAHNews_ajouter:
    path:     /ajouter_news
    defaults: { _controller: OAHNewsBundle:News:ajouter }

OAHNews_modifier:
    path:     /modifier/{id}
    defaults: { _controller: OAHNewsBundle:News:modifier }
    requirements:
        id: \d+

OAHNews_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: OAHNewsBundle:News:supprimer }
    requirements:
        id: \d+

OAHNews_categorie:
    path:    /categorie/{slug}
    defaults: { _controller: OAHNewsBundle:News:categorie }
