OAHNews_accueil:
    path:     /{page}
    defaults: { _controller: OAHNewsBundle:News:index , page: 1 }
    requirements:
        page: \d*

OAHNews_voir:
    path:     /article/{slugarticle}
    defaults: { _controller: OAHNewsBundle:News:voir }

OAHNews_ajouter:
    path:     /ajouter_article
    defaults: { _controller: OAHNewsBundle:News:ajouter }

OAHNews_modifier:
    path:     /modifier/{slugarticle}
    defaults: { _controller: OAHNewsBundle:News:modifier }

OAHNews_supprimer:
    path:     /supprimer/{slugarticle}
    defaults: { _controller: OAHNewsBundle:News:supprimer }

OAHNews_categorie:
    path:     /categorie/{slug}/{page}
    defaults: { _controller: OAHNewsBundle:News:categorie , page: 1 }
    requirements:
        page: \d*